export const SONGS = [
    {
        band: "Dashboard Confessional",
        title: "Hands Down",
        avgLineDuration: 3000,
        lyrics: [
            "Breathe in for luck, breathe in so deep",
            "This air is blessed, you share with me",
            "This night is wild, so calm and dull",
            "These hearts, they race, from self-control",
            "Your legs are smooth as they graze mine",
            "We're doing fine, we're doing nothing at all",
            { text: "", lineDuration: 3000, songDuration: 5000 },
            "My hopes are so high that your kiss might kill me",
            "So won't you kill me, so I die happy?",
            "My heart is yours to fill or burst to break or bury",
            "Or wear as jewelry, whichever you prefer",
            "The words are hushed, let's not get busted",
            "Just lay entwined here, undiscovered",
            "",
            "Safe in here from all the stupid questions",
            "\"Hey, did you get some?\" Man, that is so dumb",
            "Stay quiet, stay near, stay close, they can't hear",
            "So we can get some",
            "",
            "My hopes are so high that your kiss might kill me",
            "So won't you kill me, so I die happy?",
            "My heart is yours to fill or burst, to break or bury",
            "Or wear as jewelry, whichever you prefer",
            { text: "[Guitar Interlude]", lineDuration: 5000 },
            "Hands down, this is the best day I can",
            "Ever remember, I'll always remember the sound",
            "Of the stereo, the dim of the soft lights",
            "The scent of your hair that you twirled in your fingers",
            "And the time on the clock when we realized it's so late",
            "And this walk that we shared together",
            "The streets were wet, and the gate was locked",
            "So I jumped it and I let you in",
            "And you stood at your door with your hands on my waist",
            "And you kissed me like you meant it",
            "And I knew that you meant it, that you meant it, that you meant it",
            "And I knew that you meant it, that you meant it",
        ],
    },
    {
        band: "Green Day",
        title: "Basket Case",
        avgLineDuration: 3000,
        lyrics: [
            "Do you have the time to listen to me whine?",
            "About nothing and everything, all at once",
            "I am one of those melodramatic fools",
            "Neurotic to the bone, no doubt about it",
            "",
            "Sometimes I give myself the creeps",
            "Sometimes my mind plays tricks on me",
            "It all keeps adding up",
            "I think I'm cracking up",
            "Am I just paranoid or am I just stoned?",
            "",
            "I went to a shrink, to analyze my dreams",
            "She said it's lack of sex that's bringing me down",
            "I went to a whore, he said my life's a bore",
            "So quit my whining 'cause it's bringing her down",
            "",
            "Sometimes I give myself the creeps",
            "Sometimes my mind plays tricks on me",
            "It all keeps adding up",
            "I think, I'm cracking up",
            "Am I just paranoid?",
            "I don't know",
            { text: "[Guitar Solo]", lineDuration: 6000 },
            "Grasping to control",
            "So I better hold on",
            "",
            "Sometimes I give myself the creeps",
            "Sometimes my mind plays tricks on me",
            "It all keeps adding up",
            "I think I'm cracking up",
            "Am I just paranoid?",
            "Or am I just stoned?",
        ],
    },
    {
        band: "The Killers",
        title: "Mr. Brightside",
        avgLineDuration: 3000,
        lyrics: [
            "Coming out of my cage and I've been doing just fine",
            "Gotta, gotta be down, because I want it all",
            "It started out with a kiss, how did it end up like this?",
            "It was only a kiss, it was only a kiss",
            "Now I'm falling asleep and she's calling a cab",
            "While he's having a smoke and she's taking a drag",
            "Now they're going to bed and my stomach is sick",
            "And it's all in my head, but she's touching his",
            "",
            "Chest now, he takes off her",
            "Dress now, let me go",
            "And I just can't look, it's killing me",
            "They're taking control",
            "",
            "Jealousy, turning saints into the sea",
            "Swimming through sick lullabies, choking on your alibis",
            "But it's just the price I pay, destiny is calling me",
            "Open up my eager eyes, 'cause I'm Mr. Brightside",
            "",
            "I'm coming out of my cage and I've been doing just fine",
            "Gotta, gotta be down, because I want it all",
            "It started out with a kiss, how did it end up like this?",
            "It was only a kiss, it was only a kiss",
            "Now I'm falling asleep and she's calling a cab",
            "While he's having a smoke and she's taking a drag",
            "Now they're going to bed and my stomach is sick",
            "And it's all in my head, but she's touching his",
            "",
            "Chest now, he takes off her",
            "Dress now, let me go",
            "'Cause I just can't look, it's killing me",
            "They're taking control",
            "",
            "Jealousy, turning saints into the sea",
            "Swimming through sick lullabies, choking on your alibis",
            "But it's just the price I pay, destiny is calling me",
            "Open up my eager eyes, 'cause I'm Mr. Brightside",
            { text: "[Guitar Outro]", lineDuration: 5000 },
            "I never...",
            "I never...",
            "I never...",
            "I never...",
        ],
    },
    {
        band: "The All-American Rejects",
        title: "Move Along",
        avgLineDuration: 3000,
        lyrics: [
            "Go ahead as you waste your days with thinking",
            "When you fall, everyone stands",
            "Another day and you've had your fill of sinking",
            "With the life held in your",
            "Hands are shaking cold",
            "These hands are meant to hold (speak to me)",
            { text: "[Chorus]", lineDuration: 3000 },
            "When all you got to keep is strong",
            "Move along, move along like I know ya do",
            "And even when your hope is gone",
            "Move along, move along just to make it through",
            { text: "[Bridge]", lineDuration: 2000 },
            "Move along",
            "Move along",
            "So a day when you've lost yourself completely",
            "Could be a night when your life ends",
            "Such a heart that will lead you to deceiving",
            "All the pain held in your",
            "Hands are shaking cold",
            "Your hands are mine to hold (speak to me)",
            { text: "[Chorus]", lineDuration: 3000 },
            "When all you got to keep is strong",
            "Move along, move along like I know ya do",
            "And even when your hope is gone",
            "Move along, move along just to make it through",
            { text: "[Post-Chorus]", lineDuration: 2000 },
            "Move along",
            "When everything is wrong, we move along",
            "(Go on, go on, go on, go on)",
            "When everything is wrong, we move",
            "Along (along)",
            "Along (along)",
            "Along (along)",
            "Along (along)",
            { text: "[Outro Chorus]", lineDuration: 3000 },
            "When all you got to keep is strong",
            "Move along, move along like I know you do",
            "And even when your hope is gone",
            "Move along, move along just to make it through",
            "When all you gotta keep is strong",
            "Move along, move along like I know you do (I know you do)",
            "And even when your hope is gone",
            "Move along, move along just to make it through",
            "Move along",
            "Right back what is wrong, we move along",
            "(Go on, go on, go on, go on)",
            "Right back what is wrong, we move along",
            "Right back what is wrong, we move along",
            "(Go on, go on, go on, go on)",
            "Right back what is wrong, we move along",
            "(Go on, go on...)",
        ],
    },
    {
        band: "Smash Mouth",
        title: "All Star",
        avgLineDuration: 3000,
        lyrics: [
            "Somebody once told me the world is gonna roll me",
            "I ain't the sharpest tool in the shed",
            "She was looking kind of dumb with her finger and her thumb",
            "In the shape of an \"L\" on her forehead",
            "",
            "Well, the years start comin' and they don't stop comin'",
            "Fed to the rules and I hit the ground runnin'",
            "Didn't make sense not to live for fun",
            "Your brain gets smart, but your head gets dumb",
            "So much to do, so much to see",
            "So, what's wrong with taking the backstreets?",
            "You'll never know if you don't go (go)",
            "You'll never shine if you don't glow",
            { text: "[Chorus]", lineDuration: 3000 },
            "Hey now, you're an all-star",
            "Get your game on, go play",
            "Hey now, you're a rock star",
            "Get the show on, get paid",
            "(And all that glitters is gold)",
            "Only shootin' stars break the mold",
            { text: "[Verse 2]", lineDuration: 3000 },
            "It's a cool place, and they say it gets colder",
            "You're bundled up now, wait 'til you get older",
            "But the meteor men beg to differ",
            "Judging by the hole in the satellite picture",
            "The ice we skate is gettin' pretty thin",
            "The water's gettin' warm, so you might as well swim",
            "My world's on fire, how 'bout yours?",
            "That's the way I like it, and I'll never get bored",
            { text: "[Chorus]", lineDuration: 3000 },
            "Hey now, you're an all-star",
            "Get your game on, go play",
            "Hey now, you're a rock star",
            "Get the show on, get paid",
            "(All that glitters is gold)",
            "Only shootin' stars break the mold",
            { text: "[Bridge]", lineDuration: 3000 },
            "Go for the moon",
            "(Go, go, go) go for the moon",
            "(Go, go, go) go for the moon",
            "Go (go), go for the moon",
            { text: "[Chorus]", lineDuration: 3000 },
            "Hey now, you're an all-star",
            "Get your game on, go play",
            "Hey now, you're a rock star",
            "Get the show on, get paid",
            "(And all that glitters is gold)",
            "Only shooting stars",
            { text: "[Verse 3]", lineDuration: 3000 },
            "Somebody once asked, \"Could I spare some change for gas?",
            "I need to get myself away from this place\"",
            "I said, \"Yep, what a concept, I could use a little fuel myself",
            "And we could all use a little change\"",
            { text: "[Outro Chorus]", lineDuration: 3000 },
            "Well, the years start comin' and they don't stop comin'",
            "Fed to the rules and I hit the ground runnin'",
            "Didn't make sense not to live for fun",
            "Your brain gets smart, but your head gets dumb",
            "So much to do, so much to see",
            "So, what's wrong with taking the backstreets?",
            "You'll never know if you don't go (go!)",
            "You'll never shine if you don't glow",
            { text: "[Final Chorus]", lineDuration: 3000 },
            "Hey now, you're an all-star",
            "Get your game on, go play",
            "Hey now, you're a rock star",
            "Get the show on, get paid",
            "(And all that glitters is gold)",
            "Only shootin' stars break the mold",
            "Only shootin' stars break the mold",
            { text: "[Outro]", lineDuration: 3000 },
            "Go for the moon",
            "Go for the moon",
            "Go for the moon",
            "This is how we do it",
        ],
    },
    {
        band: "Lit",
        title: "My Own Worst Enemy",
        avgLineDuration: 3000,
        lyrics: [
            "It's no surprise to me, I'm my own worst enemy",
            "'Cause every now and then, I'm an asshole to my friends",
            "It's no surprise to me, I'm my own worst enemy",
            "'Cause every now and then, I'm an asshole to my friends",
            "",
            "Well, I'm a mess, I'm a wreck",
            "I'm a train wreck, I'm a hot mess",
            "I'm a mess, I'm a wreck",
            "I'm a train wreck, I'm a hot mess",
            { text: "...", lineDuration: 2000 },
            "It's no surprise to me, I'm my own worst enemy",
            "'Cause every now and then, I'm an asshole to my friends",
            "It's no surprise to me, I'm my own worst enemy",
            "'Cause every now and then, I'm an asshole to my friends",
        ],
    },
    {
        band: "The All-American Rejects",
        title: "Dirty Little Secret",
        avgLineDuration: 3000,
        lyrics: [
            "I got a dirty little secret, I got a dirty little secret",
            "I got a dirty little secret, I got a dirty little secret",
            "I got a dirty little secret, I got a dirty little secret",
            "I got a dirty little secret, I got a dirty little secret",
            "",
            "I'm a mess, I'm a wreck",
            "I'm a train wreck, I'm a hot mess",
            "I'm a mess, I'm a wreck",
            "I'm a train wreck, I'm a hot mess",
            { text: "...", lineDuration: 1500 },
            "I got a dirty little secret, I got a dirty little secret",
            "I got a dirty little secret, I got a dirty little secret",
            "I got a dirty little secret, I got a dirty little secret",
            "I got a dirty little secret, I got a dirty little secret",
        ],
    },
    {
        band: "Blink-182",
        title: "Dammit",
        avgLineDuration: 3000,
        lyrics: [
            "I guess this is growing up",
            "I guess this is growing up",
            "I guess this is growing up",
            "I guess this is growing up",
            "And I'm so fucking stupid",
            "I'm so fucking stupid",
            "I'm so fucking stupid",
            "I'm so fucking stupid",
            { text: "...", lineDuration: 1000 },
            "I guess this is growing up",
            "And I don't know what to do",
            "And I don't know what to say",
            "I'm just so fucking stupid",
            "I'm so fucking stupid",
            "I'm so fucking stupid",
            "I'm so fucking stupid",
            "",
            "I guess this is growing up",
            "And I don't know what to do",
            "And I don't know what to say",
            "I'm just so fucking stupid",
            "I'm so fucking stupid",
            "I'm so fucking stupid",
            "I'm so fucking stupid",
        ],
    },
    {
        band: "The Offspring",
        title: "The Kids Aren't Alright",
        avgLineDuration: 3000,
        lyrics: [
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            "I don't know what to say",
            "I don't know what to do",
            "I don't know what to say",
            "I don't know what to do",
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            { text: "...", lineDuration: 3000 },
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            "",
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
            "The kids aren't alright",
        ],
    },
    {
        band: "Fall Out Boy",
        title: "Sugar, We're Goin' Down",
        avgLineDuration: 3000,
        lyrics: [
            "Am I more than you bargained for yet?",
            "I've been dying to tell you that I've been dying to tell you",
            "And you know what they say",
            "If you love me, you should let me go",
            "And if you don't love me, you should let me go",
            "I'm just a love song",
            "I'm just a love song",
            { text: "...", lineDuration: 2500 },
            "Sugar, we're goin' down now",
            "We're goin' down now",
            "We're goin' down now",
            "Sugar, we're goin' down now",
            "We're goin' down now",
            "We're goin' down now",
            "",
            "Am I more than you bargained for yet?",
            "I've been dying to tell you that I've been dying to tell you",
            "And you know what they say",
            "If you love me, you should let me go",
            "And if you don't love me, you should let me go",
        ],
    },
    {
        band: "Jimmy Eat World",
        title: "The Middle",
        avgLineDuration: 3000,
        lyrics: [
            "Hey, don't write yourself off yet",
            "It's only in your head you feel left out or looked down on",
            "Just try your best",
            "Just try your best to find a way",
            "Just try your best to find a way to get through",
            "",
            "It's only in your head",
            "It's only in your head",
            "It's only in your head",
            "It's only in your head",
            "You feel left out or looked down on",
            "Just try your best",
            "Just try your best to find a way",
            "Just try your best to find a way to get through",
            { text: "...", lineDuration: 2500 },
            "Hey, you'll be fine",
            "Just try your best to find a way",
            "Just try your best to find a way to get through",
            "It's only in your head",
            "It's only in your head",
            "It's only in your head",
        ],
    },
    {
        band: "Paramore",
        title: "Still into You",
        avgLineDuration: 3000,
        lyrics: [
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            { text: "...", lineDuration: 2000 },
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
            "I should be over all the butterflies but I'm into you",
        ],
    },
    {
        band: "Sum 41",
        title: "Fat Lip",
        avgLineDuration: 3000,
        lyrics: [
            "I've got a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            { text: "...", lineDuration: 1000 },
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
            "I'm a fat lip, I'm a fat kid",
        ],
    },
    {
        band: "Avril Lavigne",
        title: "Sk8er Boi",
        avgLineDuration: 3000,
        lyrics: [
            "He was a boy, she was a girl",
            "Can I make it any more obvious?",
            "He was a punk, she did ballet",
            "What more can I say?",
            "He was a punk, she did ballet",
            "What more can I say?",
            "",
            "He was a sk8er boi",
            "She said see ya later boi",
            "He wasn't good enough for her",
            "Now he's a superstar",
            "Slamming on his guitar",
            "Does your pretty face get you far?",
            { text: "...", lineDuration: 2500 },
            "He was a sk8er boi",
            "She said see ya later boi",
            "He wasn't good enough for her",
            "Now he's a superstar",
            "",
            "He was a sk8er boi",
            "She said see ya later boi",
            "He wasn't good enough for her",
            "Now he's a superstar",
        ],
    },
    {
        band: "Yellowcard",
        title: "Only One",
        avgLineDuration: 3000,
        lyrics: [
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            { text: "...", lineDuration: 3000 },
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
            "I've got this feeling, something's not right",
        ],
    },
    {
        band: "Blink-182",
        title: "The Rock Show",
        avgLineDuration: 3000,
        lyrics: [
            "I am a kid, I'm a punk",
            "I'm a rebel, I'm a freak",
            "I'm a kid, I'm a punk",
            "I'm a rebel, I'm a freak",
            "And I'm gonna go to the rock show",
            "I'm gonna go to the rock show",
            { text: "...", lineDuration: 2000 },
            "I'm a kid, I'm a punk",
            "I'm a rebel, I'm a freak",
            "And I'm gonna go to the rock show",
            "I'm gonna go to the rock show",
            "",
            "I am a kid, I'm a punk",
            "I'm a rebel, I'm a freak",
            "I'm a kid, I'm a punk",
            "I'm a rebel, I'm a freak",
        ],
    },
    {
        band: "Blink-182",
        title: "First Date",
        avgLineDuration: 3000,
        lyrics: [
            "I've got a brand new car and a brand new friend",
            "I'm going to take you to the first date",
            "I'm going to take you to the first date",
            "I'm going to take you to the first date",
            "",
            "I'm so nervous",
            "I'm so nervous",
            "I'm so nervous",
            "I'm so nervous",
            { text: "...", lineDuration: 1500 },
            "I'm going to take you to the first date",
            "I'm going to take you to the first date",
            "I'm going to take you to the first date",
            "I'm going to take you to the first date",
            "",
            "I'm so nervous",
            "I'm so nervous",
            "I'm so nervous",
            "I'm so nervous",
        ],
    },
];